---
title: "test"
author: "Ayu"
date: "7/26/2023"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## read libraries
```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(orchaRd)
library(metafor)
library(MetBrewer)
```

## function 2 for this test
```{r}
effect_lnRR_test <- function(dt) {
  
  # replace 0 in "C_mean", "T_sd", "C_sd", "C_proportion" with each minimum values
  # if proportion too extreme value, replace minimum value (only "T_proportion")
  
  dt <- dt %>% 
    mutate(C_mean = ifelse(C_mean == 0, 0.04, C_mean))
  dt <- dt %>% 
    mutate(T_sd = ifelse(T_sd == 0, 0.01, T_sd))
  dt <- dt %>% 
    mutate(C_sd = ifelse(C_sd == 0, 0.05, C_sd))
  dt <- dt %>% 
    mutate(C_proportion = ifelse(C_proportion == 0, 0.01, C_proportion))
  dt <- dt %>% 
    mutate(T_proportion = ifelse(T_proportion < 0.01, 0.01, T_proportion))
  
　# copy dataset for adding effect size and its variation (lnRR /lnRR_var) column
  dt1 <- dt %>% 
    mutate(lnRR     = NA,
           lnRR_var = NA)
  
  for(i in seq_len(nrow(dt1))) {
    
    Tn <- dt1$Tn[i]
    Cn <- dt1$Cn[i]
    T_mean <- dt1$T_mean[i]
    C_mean <- dt1$C_mean[i]
    T_proportion <- dt1$T_proportion[i]
    C_proportion <- dt1$C_proportion[i]
    T_sd <- dt1$T_sd[i]
    C_sd <- dt1$C_sd[i]
    Response <- dt1$Response[i]
    Measure <- dt1$Measure[i]
    
    # continuous data - using escalc() (metafor package)
    if (Response == "continuous") {
      
      effect <- escalc(measure = "ROM", 
                       n1i = Tn, n2i = Cn, 
                       m1i = T_mean, m2 = C_mean, 
                       sd1i = T_sd, sd2i = C_sd,
                       var.names = c("lnRR", "lnRR_var")
      )
      
      dt1$lnRR[i] <- effect$lnRR
      dt1$lnRR_var[i] <- effect$lnRR_var
      
    }
    
    # proportion data (no sd values)
    else if (Response == "proportion1") {
      
      # transform proportion value
      asin_trans <- function(proportion) {
        trans <- asin(sqrt(proportion)) 
        trans
      }
      
      T_proportion <- asin_trans(T_proportion)
      C_proportion <- asin_trans(C_proportion)
      
      # calculate lnRR and lnRR variance   
      lnRR_pro1 <- log(T_proportion / C_proportion)
      lnRR_var_pro1 <- (1 / sqrt(8))^2 * (1 / (T_proportion^2 * Tn) +
                                            1 / (C_proportion^2 * Cn))
      
      dt1$lnRR[i] <- lnRR_pro1
      dt1$lnRR_var[i] <- lnRR_var_pro1
      
    }
    
    # proportion data (exist sd values) 
    else if (Response == "proportion2") {
      
      # transform proportion mean value
      asin_trans <- function(proportion) {
         trans <- asin(sqrt(proportion)) 
         trans
         }
      
      T_SD <- T_sd^2/(4*(T_proportion)*(1-(T_proportion)))
      C_SD <- C_sd^2/(4*(C_proportion)*(1-(C_proportion)))

      T_proportion <- asin_trans(T_proportion)
      C_proportion <- asin_trans(C_proportion)
      
      # calculate lnRR and lnRR variance 
      lnRR_pro2 <- log(T_proportion / C_proportion)
      lnRR_var_pro2 <- (T_SD)^2 * (1 / (T_proportion^2 * Tn)) +
                          (C_SD)^2 * (1 / (C_proportion^2 * Cn))
      
      dt1$lnRR[i] <- lnRR_pro2
      dt1$lnRR_var[i] <- lnRR_var_pro2
      
    }
  }
  
  return(dt1)
  
}

meta_am <- function(yi, V, predictor, dat){
  model1 <- rma.mv(yi = yi,
       V = V, 
       mods = ~ predictor,
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID, 
                     ~1 | Shared_control_ID),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = dat)
  
  meta_result <- summary(model1)
  
  return(meta_result)
}

```

## read datasets
```{r}
dat_prey <- read_csv(here("data/prey_22072023.csv"))
dat_pred <- read_csv(here("data/predator_22072023.csv"))
dat_all <-  read_csv(here("data/all_25072023.csv"))

dat_prey <- dat_prey[1:146,] 
dat_all <-  dat_all[1:263,] 

all_inc <- dat_all %>% filter(Direction == "Increase") 
all_dec <- dat_all %>% filter(Direction == "Decrease")
```

## response -> increase dataset
```{r}
all1 <- effect_lnRR_test(all_inc)

hist(all1$lnRR) 
hist(all1$lnRR_var)
which(all1$lnRR == min(all1$lnRR))
which(all1$lnRR == max(all1$lnRR))
```

### meta-analysis
```{r}
ma_allinc <- rma.mv(yi = lnRR,
       V = lnRR_var, 
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID,
                     ~1 | Shared_control_ID),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = all1)

summary(ma_allinc)
i2_ml(ma_allinc)

#          I2_Total          I2_Study_ID         I2_Cohort_ID I2_Shared_control_ID 
#           96.24586             36.65856             21.38058             38.20672 

# plot
p1_all_inc <-  orchard_plot(ma_allinc,
             group = "Study_ID",
             xlab = "log response ratio (lnRR)", angle = 45) +
  scale_x_discrete(labels = c("Overall effect")) +
  scale_fill_manual(values = met.brewer("Renoir")) +
  scale_colour_manual(values = met.brewer("Renoir"))
p1_all_inc

ggsave("overall_all_inc.pdf", dpi = 450)
```

### meta-regression
#### eyespot or conspicuous?
```{r}

mr_allinc1_test <- meta_am( yi = all1$lnRR, V = all1$lnRR_var, predictor = all1$Treatment_stimulus, all1)

summary(mr_allinc1_test)

# intrcpt	0.1654	0.1039	1.5914	200	0.1131	-0.0396	0.3704	
# predictoreyespot	0.1758	0.0810	2.1704	200	0.0312	0.0161	0.3355
mr_allinc1 <- rma.mv(yi = lnRR,
       V = lnRR_var, 
       mods = ~ Treatment_stimulus,
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID,
                     ~1 | Shared_control_ID),
       #R = list(Phylo = cor_tree),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = all1)

summary(mr_allinc1)
# intrcpt	0.1654	0.1039	1.5914	200	0.1131	-0.0396	0.3704	
# Treatment_stimuluseyespot	0.1758	0.0810	2.1704	200	0.0312	0.0161	0.3355

r2_ml(mr_allinc1)
#   R2_marginal R2_conditional 
#    0.02594083     0.80336336 

p2_allinc <- orchard_plot(mr_allinc1,
             mod = "Treatment_stimulus",
             group = "Study_ID",
             xlab = "log response ratio (lnRR)",
             angle = 45) +
             scale_fill_manual(values = met.brewer("Homer2", 2)) +
            scale_colour_manual(values = met.brewer("Homer2", 2))
p2_allinc

ggsave("treatment_all_inc.pdf", dpi = 450)
```

#### area of pattern
```{r}
mr_allinc2 <- rma.mv(yi = lnRR,
       V = lnRR_var, 
       mods = ~ Area_pattern,
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID, 
                     ~1 | Shared_control_ID),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = all1)

summary(mr_allinc2)
r2_ml(mr_allinc2)
#   R2_marginal R2_conditional 
#     0.3395119      0.8654739 

# plotしたいんだけどなー
bubble_plot(mr_allinc2,
             mod = "Area_pattern",
             group = "Study_ID",
             xlab = "Area (mm2)")

#FIXME - Error in `$<-.data.frame`(`*tmp*`, "condition", value = integer(0)) : 
#replacement has 0 rows, data has 200
```

#### number of pattern
```{r}
mr_allinc3 <- rma.mv(yi = lnRR,
                   V = lnRR_var, 
                   mods = ~ Number_pattern,
                   random = list(~1 | Study_ID,
                                 ~1 | Cohort_ID, 
                                 ~1 | Shared_control_ID),
                   test = "t",
                   method = "REML", 
                   sparse = TRUE,
                   data = all1)

summary(mr_allinc3)
r2_ml(mr_allinc3)
# R2_marginal R2_conditional 
# 0.02978747     0.77868041 

bubble_plot(mr_allinc3,
            mod = "Number_pattern",
            group = "Study_ID",
            xlab = "Number")

#FIXME - Error in `$<-.data.frame`(`*tmp*`, "condition", value = integer(0)) : 
#replacement has 0 rows, data has 200
```

#### type of prey
```{r}
mr_allinc4 <- rma.mv(yi = lnRR,
       V = lnRR_var, 
       mods = ~ Type_prey,
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID, 
                     ~1 | Shared_control_ID),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = all1)

summary(mr_allinc4)
r2_ml(mr_allinc4)

orchard_plot(mr_allinc4,
             mod = "Type_prey",
             group = "Study_ID",
             xlab = "Type of prey")
```

#### shape of prey
```{r}
mr_allinc5 <- rma.mv(yi = lnRR,
                   V = lnRR_var, 
                   mods = ~ Shape_prey,
                   random = list(~1 | Study_ID,
                                 ~1 | Cohort_ID, 
                                 ~1 | Shared_control_ID),
                   test = "t",
                   method = "REML", 
                   sparse = TRUE,
                   data = all1)

summary(mr_allinc5)

orchard_plot(mr_allinc5,
             mod = "Shape_prey",
             group = "Study_ID",
             xlab = "Shape of prey")

```

Response -> decrease dataset
```{r}
# decrease dataset
all2 <- effect_lnRR_test(all_dec)

hist(all2$lnRR) 
hist(all2$lnRR_var)
which(all2$lnRR == min(all2$lnRR))
which(all2$lnRR == max(all2$lnRR))


# meta-analysis
ma_all_dec <- rma.mv(yi = lnRR,
       V = lnRR_var, 
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID,
                     ~1 | Shared_control_ID),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = all2)

summary(ma_all_dec)
i2_ml(ma_all_dec)
 
#                 I2_Total              I2_Study_ID              I2_Cohort_ID            I2_Shared_control_ID 
#        9.749855e+01(97%)        2.818517e+01(28%)         6.931336e+01(69%)         1.238683e-05(almost 0%) 

# plot
p1_all_dec <-  orchard_plot(ma_all_dec,
             group = "Study_ID",
             xlab = "log response ratio (lnRR)", angle = 45) +
             scale_x_discrete(labels = c("Overall effect")) +
             scale_y_continuous(limit = c(-2.5, 4.5)) +
             scale_fill_manual(values = met.brewer("Renoir", direction = -1)) +
             scale_colour_manual(values = met.brewer("Renoir", direction = -1))
p1_all_dec

ggsave("overall_all_inc.pdf", dpi = 450)
```
#### area of pattern
```{r}
mr_alldec2 <- rma.mv(yi = lnRR,
       V = lnRR_var, 
       mods = ~ Area_pattern,
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID, 
                     ~1 | Shared_control_ID),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = all2)

summary(mr_alldec2)
r2_ml(mr_alldec2)
#   R2_marginal R2_conditional 
#     0.3395119      0.8654739 

# plotしたいんだけどなー
bubble_plot(mr_alldec2,
             mod = "Area_pattern",
             group = "Study_ID",
             xlab = "Area (mm2)")

#FIXME - Error in `$<-.data.frame`(`*tmp*`, "condition", value = integer(0)) : 
#replacement has 0 rows, data has 200
```

#### number of pattern
```{r}
mr_alldec3 <- rma.mv(yi = lnRR,
                   V = lnRR_var, 
                   mods = ~ Number_pattern,
                   random = list(~1 | Study_ID,
                                 ~1 | Cohort_ID, 
                                 ~1 | Shared_control_ID),
                   test = "t",
                   method = "REML", 
                   sparse = TRUE,
                   data = all2)

summary(mr_alldec3)
r2_ml(mr_alldec3)
# R2_marginal R2_conditional 
# 0.02978747     0.77868041 

bubble_plot(mr_alldec3,
            mod = "Number_pattern",
            group = "Study_ID",
            xlab = "Number")

#FIXME - Error in `$<-.data.frame`(`*tmp*`, "condition", value = integer(0)) : 
#replacement has 0 rows, data has 200
```

#### type of prey
```{r}
mr_alldec4 <- rma.mv(yi = lnRR,
       V = lnRR_var, 
       mods = ~ Type_prey,
       random = list(~1 | Study_ID,
                     ~1 | Cohort_ID, 
                     ~1 | Shared_control_ID),
       test = "t",
       method = "REML", 
       sparse = TRUE,
       data = all2)

summary(mr_alldec4)

orchard_plot(mr_alldec4,
             mod = "Type_prey",
             group = "Study_ID",
             xlab = "Type of prey")
```

#### shape of prey
```{r}
mr_alldec5 <- rma.mv(yi = lnRR,
                   V = lnRR_var, 
                   mods = ~ Shape_prey,
                   random = list(~1 | Study_ID,
                                 ~1 | Cohort_ID, 
                                 ~1 | Shared_control_ID),
                   test = "t",
                   method = "REML", 
                   sparse = TRUE,
                   data = all2)

summary(mr_alldec5)

orchard_plot(mr_alldec5,
             mod = "Shape_prey",
             group = "Study_ID",
             xlab = "Shape of prey")

```

